unicorn/apps/api/urls.py
from django.urls import include, path, register_converter

from .views import (
    GetBrightnessView,
    GetColorView,
    GetStatusView,
    SetColorView,
    SetStatusView,
)


class HexColorConverter:
    regex = '[0-9,a-f,A-F]{6}'

    def to_python(self, value):
        return str(value)

    def to_url(self, value):
        return value.lower()


class OnOffConverter:
    regex = 'on|off'

    def to_python(self, value):
        return str(value)

    def to_url(self, value):
        return value.lower()


register_converter(HexColorConverter, 'hexcolor')
register_converter(OnOffConverter, 'onoff')

app_name = 'api'

urlpatterns = [
    path('v1.0/', include([
        path('status', GetStatusView.as_view(), name='get-status'),
        path('status/<onoff:status>/', SetStatusView.as_view(), name='set-status'),
        path('on', SetStatusView.as_view(), {'status': 'on'}, name='set-status-on'),
        path('off', SetStatusView.as_view(), {'status': 'off'}, name='set-status-off'),
        path('color', GetColorView.as_view(), name='get-color'),
        path('color/<hexcolor:color>', SetColorView.as_view(), name='set-color'),
        path('brightness', GetBrightnessView.as_view(), name='get-brightness'),
    ])),
]

unicorn/apps/config/urls.py
from django.urls import include, path, register_converter

from .views import ConfigureHomeView, WifiConfigView, WifiConfigUpdatingView


app_name = 'config'

urlpatterns = [
    path('', ConfigureHomeView.as_view(), name='configure-home'),
    path('wifi/', include([
        path('', WifiConfigView.as_view(), name='configure-wifi'),
        path('updating/', WifiConfigUpdatingView.as_view(), name='updating-wifi'),
    ])),
]

unicorn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('config/', include('unicorn.apps.config.urls')),
    path('unicorn/api/', include('unicorn.apps.api.urls'))
]

unicorn/apps/config/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _


SECURITY_MODES = [
    ('WEP', _('WEP')),
    ('WPA_WPA2P', _('WPA/WPA2 Personal')),
    ('WPA2P', _('WPA2 Personal')),
]


class WifiConfigForm(forms.Form):
    BAD_SSID_CHARS = '+]"\t'
    BAD_FIRST_SSID_CHARS = '!#;'

    ssid = forms.CharField(
        label=_('Station ID'),
        required=True,
    )
    password = forms.CharField(
        label=_('WiFi Password'),
        required=False,
        widget=forms.PasswordInput,
    )
    security_mode = forms.ChoiceField(
        label=_('Security mode'),
        choices=SECURITY_MODES,
    )

    def clean_ssid(self):
        """
        The SSID can consist of up to 32 alphanumeric, case-sensitive,
        characters. The first character cannot be the !, #, or ; character.
        The +, ], /, ", TAB, and trailing spaces are invalid characters
        for SSIDs.

        However, I know for a fact that the "/" is accepted in SSIDs!
        """
        ssid = self.cleaned_data['ssid'].strip()

        if ssid[0] in self.BAD_FIRST_SSID_CHARS:
            raise ValidationError(
                "The SSID should not contain '{}' as the "
                "first symbol.".format(ssid[0]))

        illegal_chars = set(ssid) & set(self.BAD_SSID_CHARS)
        if len(illegal_chars) == 1:
            raise ValidationError(
                "The SSID should not contain the '{}' "
                "symbol.".format(illegal_chars[0]))
        elif len(illegal_chars) > 1:
            illegal_chars_for_display = ", ".join(illegal_chars)
            raise ValidationError(
                "The SSID should not contain any of these symbols: "
                "{}.".format(illegal_chars_for_display))

unicorn/apps/api/views.py
from django.http import HttpResponse
from django.views.generic import View

from unicorn.apps.color import Color
from unicorn.apps.unicorn_phat.unicorn import unicorn_phat

OK = 'OK'


class BaseApiView(View):
   http_method_names = ['get', ]


class GetStatusView(BaseApiView):
    """
    Returns the on/off status of the lamp.
    """
    def get(self, request, *args, **kwargs):
        return HttpResponse("1" if unicorn_phat.status else "0")


class SetStatusView(BaseApiView):
    """
    Sets the on/off status of the lamp.
    """
    def get(self, request, *args, **kwargs):
        status = self.kwargs.get('status')
        unicorn_phat.set_status(status == 'on')
        return HttpResponse(OK)


class GetColorView(BaseApiView):
    """
    Returns the current color of the lamp.
    """
    def get(self, request, *args, **kwargs):
        return HttpResponse(unicorn_phat.color.as_hex())


class SetColorView(BaseApiView):
    """
    Sets the color of the lamp.
    """
    def get(self, request, *args, **kwargs):
        color = self.kwargs.get('color')
        unicorn_phat.set_color(Color(hex=color))
        return HttpResponse(OK)


class GetBrightnessView(BaseApiView):
    """
    Returns the brightness of the lamp (based on its current color values).
    """
    def get(self, request, *args, **kwargs):
        return HttpResponse(unicorn_phat.color.brightness)

unicorn/apps/config/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from .forms import WifiConfigForm


class ConfigureHomeView(TemplateView):
    template_name = 'config/home.html'


class WifiConfigView(FormView):
    http_method_names = ['get', 'post', ]
    form_class = WifiConfigForm
    template_name = 'config/wifi_config.html'
    success_url = reverse_lazy('updating-wifi')


class WifiConfigUpdatingView(TemplateView):
    template_name = 'config/wifi_updating.html'

    def get(self, request, *args, **kwargs):
        # TODO: Set the parameters
        return super().get(request, *args, **kwargs)

unicorn/apps/config/templates/config/home.html
{% extends "base.html" %}

{% block page_title %}Configuration: Home{% endblock %}
{% block title %}Configuration: Home{% endblock %}

{% block content %}
    {{ super }}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <p class="text-muted"></p>
            </div>
        </div>
    </div>
{% endblock %}

unicorn/apps/config/templates/config/wifi_config.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}Configuration: Wifi{% endblock %}
{% block title %}Configuration: Wifi{% endblock %}

{% block content %}
    {{ super }}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h2>Wi-Fi Configuration</h2>
                <p class="text-muted">Connect your lamp to your local wifi network</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_ssid">{% trans "Station ID:" %}</label>
                        <input type="text" class="form-control" name="ssid" required="required" id="id_ssid" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="id_password">{% trans "Wifi Password:" %}</label>
                        <input type="password" class="form-control" name="password" required="required" id="id_password" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="id_security_mode">{% trans "Security Mode:" %}</label>
                        <select class="form-control" name="security_mode" id="id_security_mode">
                            <option value="WEP">WEP</option>
                            <option value="WPA_WPA2P">WPA/WPA2 Personal</option>
                            <option value="WPA2P">WPA2 Personal</option>
                        </select>
                    </div>
                    <input class="btn btn-primary" id="submit" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

unicorn/apps/config/templates/config/wifi_updating.html
{% extends "base.html" %}

{% block page_title %}Updating Wifi{% endblock %}
{% block title %}Updating Wifi{% endblock %}

{% block content %}
    {{ super }}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <p class="text-muted">The Wi-Fi settings are being updated.</p>
            </div>
        </div>
    </div>
{% endblock %}

unicorn/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block page_title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
    </head>
    <body class="pt-4 mt-5">
        {% block navbar %}
            <nav class="navbar fixed-top navbar-expand-md navbar-light bg-light">
              <a class="navbar-brand" href="{% url 'config:configure-home' %}">{% trans "Homebridge Pi Lamp" %}</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'config:configure-home' %}">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'config:configure-wifi' %}">Wifi <span class="sr-only">(current)</span></a>
                  </li>
                </ul>
              </div>
            </nav>
        {% endblock %}
        {% block content %}
        {% endblock %}
        {% block js %}
            <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
            <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
        {% endblock %}
    </body>
</html>